-- Le propriétaire est lié à l'enfant lors de la création, via une fonction RPC sécurisée.
drop policy "guardians manage child" on public.children;
create policy "guardians read child" on public.children for select using (exists(select 1 from public.child_guardians g where g.child_id=id and g.user_id=auth.uid()));
create policy "owners update child" on public.children for update using (exists(select 1 from public.child_guardians g where g.child_id=id and g.user_id=auth.uid() and g.is_owner));
create or replace function public.create_child(p_full_name text,p_date_of_birth date,p_sex public.child_sex,p_zone_id uuid default null) returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; begin insert into public.children(full_name,date_of_birth,sex,zone_id) values(p_full_name,p_date_of_birth,p_sex,p_zone_id) returning id into v_id; insert into public.child_guardians(child_id,user_id,is_owner) values(v_id,auth.uid(),true); return v_id; end; $$;
revoke all on function public.create_child(text,date,public.child_sex,uuid) from public; grant execute on function public.create_child(text,date,public.child_sex,uuid) to authenticated;

-- Préparation des phases 2 et 3 : pas encore exposées dans l'interface.
create type public.report_category as enum ('water_contamination','water_outage','sanitation','suspected_outbreak','other');
create type public.report_urgency as enum ('low','medium','high','critical');
create type public.alert_status as enum ('detected','verified','active','resolved','cancelled');
create type public.notification_channel as enum ('web_push','sms','whatsapp','ussd');
create table public.content_items (id uuid primary key default gen_random_uuid(), kind text not null, status public.content_status not null default 'draft', audience_min_age_months smallint, audience_max_age_months smallint, created_by uuid references public.profiles(id), published_at timestamptz);
create table public.content_translations (content_id uuid references public.content_items(id) on delete cascade, language_code text not null, title text not null, body text not null, primary key(content_id,language_code));
create table public.community_posts (id uuid primary key default gen_random_uuid(), author_id uuid references public.profiles(id), zone_id uuid references public.zones(id), body text not null, status text not null default 'visible', created_at timestamptz not null default now());
create table public.water_points (id uuid primary key default gen_random_uuid(), zone_id uuid references public.zones(id), name text, point_type text, status text not null default 'unknown', latitude numeric(9,6), longitude numeric(9,6), updated_at timestamptz not null default now());
create table public.community_reports (id uuid primary key default gen_random_uuid(), reporter_id uuid references public.profiles(id), zone_id uuid references public.zones(id), water_point_id uuid references public.water_points(id), category public.report_category not null, urgency public.report_urgency not null default 'low', source text not null default 'form', description text, reported_at timestamptz not null default now(), status text not null default 'received');
create table public.alerts (id uuid primary key default gen_random_uuid(), zone_id uuid references public.zones(id), category public.report_category, severity public.report_urgency not null, status public.alert_status not null default 'detected', title text not null, started_at timestamptz not null default now(), resolved_at timestamptz);
create table public.alert_evidence (alert_id uuid references public.alerts(id) on delete cascade, report_id uuid references public.community_reports(id) on delete cascade, primary key(alert_id,report_id));
create table public.notification_preferences (user_id uuid primary key references public.profiles(id) on delete cascade, enabled_channels public.notification_channel[] not null default array['web_push']::public.notification_channel[]);
create table public.notification_intents (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id), alert_id uuid references public.alerts(id), kind text not null, scheduled_for timestamptz, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.notification_deliveries (id uuid primary key default gen_random_uuid(), intent_id uuid references public.notification_intents(id) on delete cascade, channel public.notification_channel not null, status text not null default 'queued', provider_message_id text, sent_at timestamptz);
create table public.analytics_aggregate_snapshots (id uuid primary key default gen_random_uuid(), zone_id uuid references public.zones(id), metric text not null, period_start date not null, period_end date not null, value jsonb not null, min_population integer not null default 20, created_at timestamptz not null default now());
create index community_reports_cluster on public.community_reports(zone_id,category,reported_at desc); create index alerts_zone_status on public.alerts(zone_id,status,started_at desc); create index community_posts_feed on public.community_posts(zone_id,created_at desc) where status='visible';
